INSERT INTO `bisaitimu` VALUES (NULL, 'worse', 'A、更坏的', 'B、最坏的', 'C、有价值的', 'D、没有价值的', 'A、更坏的');
INSERT INTO `bisaitimu` VALUES (NULL, 'worthwhile', 'A、值得做的', 'B、值得的', 'C、将会', 'D、伤,伤害', 'A、值得做的');
INSERT INTO `bisaitimu` VALUES (NULL, 'wounded', 'A、受伤的', 'B、摔跤', 'C、皱纹', 'D、手腕', 'A、受伤的');
INSERT INTO `bisaitimu` VALUES (NULL, 'X-ray', 'A、著述', 'B、书写', 'C、错误', 'D、X射线', 'D、X射线');
INSERT INTO `bisaitimu` VALUES (NULL, 'survey ', 'A、调查', 'B、合计', 'C、心烦意乱的', 'D、使不安', 'A、survey ');
INSERT INTO `bisaitimu` VALUES (NULL, 'concern ', 'A、关心', 'B、遛狗', 'C、松开的', 'D、(使)担忧', 'D、使）担忧');
INSERT INTO `bisaitimu` VALUES (NULL, 'German', 'A、纳粹党人', 'B、德国人', 'C、记下', 'D、一连串的', 'B、德国人');
INSERT INTO `bisaitimu` VALUES (NULL, 'outdoors ', 'A、故意', 'B、为了……', 'C、黄昏', 'D、在户外', 'D、在户外');
INSERT INTO `bisaitimu` VALUES (NULL, 'power', 'A、面对面地', 'B、窗帘', 'C、能力', 'D、积满灰尘的', 'C、能力');
INSERT INTO `bisaitimu` VALUES (NULL, 'settle', 'A、重新获得', 'B、遭受', 'C、孤单', 'D、安家', 'D、安家');
INSERT INTO `bisaitimu` VALUES (NULL, 'get', 'A、打行李', 'B、手提箱', 'C、对……厌烦', 'D、大衣', 'C、对……厌烦');
INSERT INTO `bisaitimu` VALUES (NULL, 'exactly', 'A、感激的', 'B、确实如此', 'C、不同意', 'D、不喜欢', 'B、确实如此');
INSERT INTO `bisaitimu` VALUES (NULL, 'join in', 'A、揭示', 'B、加入', 'C、第二', 'D、项目', 'B、加入');
INSERT INTO `bisaitimu` VALUES (NULL, 'subway', 'A、汽油', 'B、电梯', 'C、地下人行道', 'D、因为', 'C、地下人行道');
INSERT INTO `bisaitimu` VALUES (NULL, 'apartment ', 'A、以…为根据', 'B、单元住宅', 'C、现在', 'D、逐渐的', 'B、实际上');
INSERT INTO `bisaitimu` VALUES (NULL, 'vocabulary ', 'A、较后的', 'B、利用', 'C、拼写', '词汇量', 'D、词汇量');
INSERT INTO `bisaitimu` VALUES (NULL, 'fluent ', 'A、例如……', 'B、频繁的', 'C、流畅的', 'D、命令', 'C、流畅的');
INSERT INTO `bisaitimu` VALUES (NULL, 'expression', 'A、中西部的', 'B、表示', 'C、东方的', 'D、辨认出', 'B、表示');
INSERT INTO `bisaitimu` VALUES (NULL, 'cab', 'A、鲶鱼', 'B、闪电', 'C、街区', 'D、出租车', 'D、出租车');
INSERT INTO `bisaitimu` VALUES (NULL, 'journal', 'A、运输', 'B、定期刊物', 'C、不利条件', 'D、费用', 'B、定期刊物');
INSERT INTO `bisaitimu` VALUES (NULL, 'finally ', 'A、最后', 'B、时间表', 'C、喜爱的', 'D、喜欢', 'A、最后');
INSERT INTO `bisaitimu` VALUES (NULL, 'shortcoming ', 'A、缺点', 'B、顽固的', 'C、组织', 'D、关心', 'A、缺点');
INSERT INTO `bisaitimu` VALUES (NULL, 'journey ', 'A、海拔高度', 'B、旅程', 'C、投降', 'D、地图；', 'B、旅程');
INSERT INTO `bisaitimu` VALUES (NULL, 'valley ', 'A、流域', 'B、缓慢而行', 'C、拐角', 'D、使弯曲', 'A、流域');
INSERT INTO `bisaitimu` VALUES (NULL, 'as usual', 'A、照常', 'B、可信赖的', 'C、观看', 'D、枕头', 'A、照常');
INSERT INTO `bisaitimu` VALUES (NULL, 'temple', 'A、庙宇', 'B、洞穴', 'C、地震', 'D、立刻', 'A、 庙宇');
INSERT INTO `bisaitimu` VALUES (NULL, 'well ', 'A、发臭的', 'B、井', 'C、农场', 'D、百万', 'B、井');
INSERT INTO `bisaitimu` VALUES (NULL, 'canal', 'A、蒸汽', 'B、水道', 'C、污垢', 'D、破败不堪', 'B、水道');
INSERT INTO `bisaitimu` VALUES (NULL, 'ruin', 'A、严重受损', 'B、使破产', 'C、苦难', 'D、极度的', 'B、使破产');
INSERT INTO `bisaitimu` VALUES (NULL, 'destroy', 'A、破坏', 'B、水坝', 'C、轨道', 'D、无用的', 'A、破坏');
